server:
  port: 9000
spring:
  application:
    name: sca-gateway
  cloud:
    gateway:
      routes:
        - id: route01
          uri: http://localhost:8081/
          predicates: ###匹配规则
            - Path=/nacos/provider/echo/**
          filters:
            - StripPrefix=1 #转发之前去掉path中第一层路径，例如nacos